import ExcelJS from "exceljs";
import { formatBDT } from "@/lib/timezone";
import type {
  MedicineInventoryReport,
  MedicinePurchase,
  MedicineSale,
  ReportMedicine,
} from "../../types";
import {
  MEDICINE_REPORT_TARGET_LABELS,
  type MedicineReportInput,
  type MedicineReportTarget,
} from "./types";
import { getGroupedStockRows } from "./stockReportHelpers";

const EXCEL_MIME_TYPE =
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
const HEADER_COLOR = "FF0F766E";
const TITLE_COLOR = "FF0F172A";
const GROUP_COLOR = "FFDBEAFE";
const BORDER_COLOR = "FFD1D5DB";

type ExcelCellValue = string | number | Date;

const safeText = (value: string | null | undefined, fallback = "N/A") => {
  if (!value || value.trim().length === 0) {
    return fallback;
  }

  return value.trim();
};

const displayMedicineName = (medicine: {
  brandName?: string | null;
  genericName: string;
}) => safeText(medicine.brandName || medicine.genericName);

const displayDate = (value: string | null | undefined): ExcelCellValue => {
  if (!value) {
    return "N/A";
  }

  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? safeText(value) : date;
};

const displayDateText = (value: string | null | undefined): string => {
  if (!value) {
    return "N/A";
  }

  const date = new Date(value);
  return Number.isNaN(date.getTime())
    ? safeText(value)
    : formatBDT(date, "dd MMM yyyy");
};

const columnLetter = (columnNumber: number): string => {
  let result = "";
  let current = columnNumber;

  while (current > 0) {
    const remainder = (current - 1) % 26;
    result = String.fromCharCode(65 + remainder) + result;
    current = Math.floor((current - 1) / 26);
  }

  return result;
};

const applyWorksheetDefaults = (worksheet: ExcelJS.Worksheet) => {
  worksheet.properties.defaultRowHeight = 18;
  worksheet.pageSetup = {
    orientation: "landscape",
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    paperSize: 9,
    margins: {
      left: 0.3,
      right: 0.3,
      top: 0.5,
      bottom: 0.5,
      header: 0.2,
      footer: 0.2,
    },
  };
};

const applyBorder = (cell: ExcelJS.Cell) => {
  cell.border = {
    top: { style: "thin", color: { argb: BORDER_COLOR } },
    left: { style: "thin", color: { argb: BORDER_COLOR } },
    bottom: { style: "thin", color: { argb: BORDER_COLOR } },
    right: { style: "thin", color: { argb: BORDER_COLOR } },
  };
};

const styleTitle = (worksheet: ExcelJS.Worksheet, title: string, columnCount: number) => {
  const lastColumn = columnLetter(columnCount);
  worksheet.mergeCells(`A1:${lastColumn}1`);
  const titleCell = worksheet.getCell("A1");
  titleCell.value = title;
  titleCell.font = { bold: true, size: 16, color: { argb: TITLE_COLOR } };
  titleCell.alignment = { horizontal: "center", vertical: "middle" };
  worksheet.getRow(1).height = 28;
};

const addMetadata = (
  worksheet: ExcelJS.Worksheet,
  periodLabel: string,
  generatedBy: string,
  columnCount: number,
) => {
  const lastColumn = columnLetter(columnCount);
  worksheet.mergeCells(`A2:${lastColumn}2`);
  worksheet.getCell("A2").value = `Period: ${periodLabel}`;
  worksheet.getCell("A2").font = { italic: true, color: { argb: "FF475569" } };
  worksheet.getCell("A2").alignment = { horizontal: "center" };

  worksheet.mergeCells(`A3:${lastColumn}3`);
  worksheet.getCell("A3").value = `Generated by: ${safeText(generatedBy)}`;
  worksheet.getCell("A3").font = { italic: true, color: { argb: "FF475569" } };
  worksheet.getCell("A3").alignment = { horizontal: "center" };
};

const addHeader = (
  worksheet: ExcelJS.Worksheet,
  headers: string[],
  widths: number[],
) => {
  const row = worksheet.addRow(headers);
  row.height = 24;
  row.font = { bold: true, color: { argb: "FFFFFFFF" } };
  row.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: HEADER_COLOR },
  };
  row.alignment = { horizontal: "center", vertical: "middle", wrapText: true };
  row.eachCell((cell) => applyBorder(cell));

  worksheet.columns = headers.map((_header, index) => ({
    key: `column${index + 1}`,
    width: widths[index] ?? 18,
  }));
  worksheet.views = [{ state: "frozen", ySplit: row.number }];
  worksheet.autoFilter = {
    from: { row: row.number, column: 1 },
    to: { row: row.number, column: headers.length },
  };

  return row.number;
};

const formatDataRows = (
  worksheet: ExcelJS.Worksheet,
  firstDataRow: number,
  numberColumns: number[],
  dateColumns: number[],
) => {
  for (let rowNumber = firstDataRow; rowNumber <= worksheet.rowCount; rowNumber += 1) {
    const row = worksheet.getRow(rowNumber);
    row.eachCell((cell, columnNumber) => {
      applyBorder(cell);
      cell.alignment = { vertical: "middle", wrapText: true };

      if (numberColumns.includes(columnNumber)) {
        cell.numFmt = "#,##0.00";
      }

      if (dateColumns.includes(columnNumber)) {
        cell.numFmt = "dd mmm yyyy";
      }
    });

    if (rowNumber % 2 === 0) {
      row.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FFF8FAFC" },
      };
    }
  }
};

const addGroupedStockTable = (
  worksheet: ExcelJS.Worksheet,
  title: string,
  medicines: ReportMedicine[],
  includeThreshold: boolean,
  showSectionTitle = true,
) => {
  const headers = [
    "Medicine Group",
    "Medicines",
    "Purchase",
    "Sales",
    "Stock in Hand",
    ...(includeThreshold ? ["Threshold"] : []),
  ];
  const widths = includeThreshold
    ? [28, 34, 16, 16, 20, 16]
    : [30, 36, 16, 16, 20];
  const lastColumn = columnLetter(headers.length);

  if (showSectionTitle) {
    const titleRow = worksheet.addRow([]).number;
    worksheet.mergeCells(`A${titleRow}:${lastColumn}${titleRow}`);
    worksheet.getCell(`A${titleRow}`).value = title;
    worksheet.getCell(`A${titleRow}`).font = {
      bold: true,
      color: { argb: TITLE_COLOR },
    };
    worksheet.getCell(`A${titleRow}`).fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: GROUP_COLOR },
    };
  }

  const headerRow = addHeader(worksheet, headers, widths);
  const groupedRows = getGroupedStockRows(medicines, includeThreshold);
  const groupRows: number[] = [];
  let totalRow = 0;

  if (groupedRows.length === 1 && groupedRows[0]?.kind === "total") {
    const emptyRow = worksheet.addRow(["No medicines found for this report."]);
    worksheet.mergeCells(`A${emptyRow.number}:${lastColumn}${emptyRow.number}`);
  } else {
    groupedRows.forEach((row) => {
      const values: ExcelCellValue[] = [
        row.groupName,
        row.medicineName,
        row.purchaseQuantity,
        row.salesQuantity,
        row.stockInHand,
      ];
      if (includeThreshold) {
        values.push(row.threshold ?? "—");
      }

      const addedRow = worksheet.addRow(values);
      if (row.kind === "group") groupRows.push(addedRow.number);
      if (row.kind === "total") totalRow = addedRow.number;
    });
  }

  formatDataRows(
    worksheet,
    headerRow + 1,
    includeThreshold ? [3, 4, 5, 6] : [3, 4, 5],
    [],
  );

  groupRows.forEach((rowNumber) => {
    const row = worksheet.getRow(rowNumber);
    row.font = { bold: true, color: { argb: TITLE_COLOR } };
    row.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: GROUP_COLOR },
    };
  });

  if (totalRow > 0) {
    const row = worksheet.getRow(totalRow);
    row.font = { bold: true, color: { argb: TITLE_COLOR } };
    row.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFF1F5F9" },
    };
  }
};

const addSummarySheet = (
  workbook: ExcelJS.Workbook,
  input: MedicineReportInput,
) => {
  const worksheet = workbook.addWorksheet("Summary");
  applyWorksheetDefaults(worksheet);
  styleTitle(
    worksheet,
    `${MEDICINE_REPORT_TARGET_LABELS[input.target]} Excel Report`,
    6,
  );
  addMetadata(worksheet, input.periodLabel, input.generatedBy, 6);

  const summaryHeaderRow = addHeader(
    worksheet,
    ["Metric", "Value", "Details", "Source"],
    [30, 18, 44, 20],
  );

  const { stats } = input.report;
  const summaryRows: ExcelCellValue[][] = [
    ["Available medicines", stats.totalMedicines, "Active medicines with stock above zero", "Inventory"],
    ["Low-stock medicines", stats.lowStockCount, "Current stock at or below threshold", "Inventory"],
    ["Stock value (BDT)", stats.totalStockValue, "Current stock × latest purchase unit cost", "Inventory"],
    ["Purchase records", stats.totalPurchasesCount, stats.totalPurchasesAmount, "Purchases"],
    ["Sales records", stats.totalSalesCount, stats.totalSalesAmount, "Sales"],
  ];

  summaryRows.forEach((rowValues) => worksheet.addRow(rowValues));
  worksheet.getCell(`B${summaryHeaderRow + 3}`).numFmt = "#,##0.00";
  worksheet.getCell(`C${summaryHeaderRow + 4}`).numFmt = "#,##0.00";
  worksheet.getCell(`C${summaryHeaderRow + 5}`).numFmt = "#,##0.00";
  formatDataRows(worksheet, summaryHeaderRow + 1, [2, 3], []);

  if (input.target === "available" || input.target === "combined") {
    addGroupedStockTable(
      worksheet,
      "Available Stock by Medicine Group",
      input.report.availableMedicines,
      false,
    );
  }

  if (input.target === "lowStock" || input.target === "combined") {
    addGroupedStockTable(
      worksheet,
      "Low Stock by Medicine Group",
      input.report.lowStockMedicines,
      true,
    );
  }
};

const addGroupedStockSheet = (
  workbook: ExcelJS.Workbook,
  name: string,
  title: string,
  medicines: ReportMedicine[],
  periodLabel: string,
  generatedBy: string,
  includeThreshold: boolean,
) => {
  const worksheet = workbook.addWorksheet(name);
  applyWorksheetDefaults(worksheet);
  const columnCount = includeThreshold ? 6 : 5;
  styleTitle(worksheet, title, columnCount);
  addMetadata(worksheet, periodLabel, generatedBy, columnCount);
  addGroupedStockTable(worksheet, title, medicines, includeThreshold, false);
};

const addPurchaseSheet = (
  workbook: ExcelJS.Workbook,
  purchases: MedicinePurchase[],
  periodLabel: string,
  generatedBy: string,
) => {
  const worksheet = workbook.addWorksheet("Purchases");
  applyWorksheetDefaults(worksheet);
  styleTitle(worksheet, "Medicine Purchases", 14);
  addMetadata(worksheet, periodLabel, generatedBy, 14);

  const headerRow = addHeader(
    worksheet,
    [
      "Purchase Date",
      "Invoice Number",
      "Company",
      "Medicine Group",
      "Medicine",
      "Generic Name",
      "Quantity",
      "Remaining Quantity",
      "Unit Price (BDT)",
      "VAT + Tax (BDT)",
      "Discount (BDT)",
      "Total Amount (BDT)",
      "Expiry Date",
      "Batch Number",
    ],
    [18, 18, 24, 22, 28, 28, 14, 20, 18, 18, 18, 20, 18, 18],
  );

  purchases.forEach((purchase) => {
    worksheet.addRow([
      displayDate(purchase.purchaseDate),
      safeText(purchase.invoiceNumber),
      safeText(purchase.company.name),
      safeText(purchase.medicine.group.name, "Unknown Group"),
      displayMedicineName(purchase.medicine),
      safeText(purchase.medicine.genericName),
      purchase.quantity,
      purchase.remainingQty,
      purchase.unitPrice,
      purchase.vatTax,
      purchase.discountAmount,
      purchase.totalAmount,
      displayDate(purchase.expiryDate),
      safeText(purchase.batchNumber),
    ]);
  });

  if (purchases.length === 0) {
    const emptyRow = worksheet.addRow(["No purchase records found for this report."]);
    worksheet.mergeCells(`A${emptyRow.number}:N${emptyRow.number}`);
  }

  formatDataRows(worksheet, headerRow + 1, [7, 8, 9, 10, 11, 12], [1, 13]);
};

const addSalesSheet = (
  workbook: ExcelJS.Workbook,
  sales: MedicineSale[],
  periodLabel: string,
  generatedBy: string,
) => {
  const worksheet = workbook.addWorksheet("Sales");
  applyWorksheetDefaults(worksheet);
  styleTitle(worksheet, "Medicine Sales", 13);
  addMetadata(worksheet, periodLabel, generatedBy, 13);

  const headerRow = addHeader(
    worksheet,
    [
      "Sale Date",
      "Patient",
      "Patient Phone",
      "Admission Number",
      "Medicine Group",
      "Medicine",
      "Generic Name",
      "Quantity",
      "Unit Price (BDT)",
      "Total Amount (BDT)",
      "Purchase Invoice",
      "Batch Number",
      "Company",
    ],
    [18, 26, 18, 20, 22, 28, 28, 14, 18, 20, 20, 18, 24],
  );

  sales.forEach((sale) => {
    worksheet.addRow([
      displayDate(sale.saleDate),
      safeText(sale.patient.fullName),
      safeText(sale.patient.phoneNumber),
      safeText(sale.admission?.admissionNumber),
      safeText(sale.medicine.group.name, "Unknown Group"),
      displayMedicineName(sale.medicine),
      safeText(sale.medicine.genericName),
      sale.quantity,
      sale.unitPrice,
      sale.totalAmount,
      safeText(sale.purchase.invoiceNumber),
      safeText(sale.purchase.batchNumber),
      safeText(sale.purchase.company.name),
    ]);
  });

  if (sales.length === 0) {
    const emptyRow = worksheet.addRow(["No sales records found for this report."]);
    worksheet.mergeCells(`A${emptyRow.number}:M${emptyRow.number}`);
  }

  formatDataRows(worksheet, headerRow + 1, [8, 9, 10], [1]);
};

const getFileName = (target: MedicineReportTarget): string => {
  const targetName = MEDICINE_REPORT_TARGET_LABELS[target]
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  const datePart = new Date().toISOString().slice(0, 10);
  return `medicine-inventory-${targetName}-${datePart}.xlsx`;
};

const downloadWorkbook = async (workbook: ExcelJS.Workbook, fileName: string) => {
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: EXCEL_MIME_TYPE });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
};

export const buildMedicineInventoryWorkbook = (
  input: MedicineReportInput,
): ExcelJS.Workbook => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = input.generatedBy;
  workbook.created = new Date();
  workbook.modified = new Date();
  workbook.title = `${MEDICINE_REPORT_TARGET_LABELS[input.target]} Excel Report`;
  workbook.subject = "Feroza Nursing Home medicine inventory";

  addSummarySheet(workbook, input);

  if (input.target === "available" || input.target === "combined") {
    addGroupedStockSheet(
      workbook,
      "Available Stock",
      "Available Stock Excel Report",
      input.report.availableMedicines,
      input.periodLabel,
      input.generatedBy,
      false,
    );
  }

  if (input.target === "lowStock" || input.target === "combined") {
    addGroupedStockSheet(
      workbook,
      "Low Stock",
      "Low-Stock Medicines by Group",
      input.report.lowStockMedicines,
      input.periodLabel,
      input.generatedBy,
      true,
    );
  }

  if (input.target === "purchases" || input.target === "combined") {
    addPurchaseSheet(
      workbook,
      input.report.purchases,
      input.periodLabel,
      input.generatedBy,
    );
  }

  if (input.target === "sales" || input.target === "combined") {
    addSalesSheet(
      workbook,
      input.report.sales,
      input.periodLabel,
      input.generatedBy,
    );
  }

  return workbook;
};

export const exportMedicineInventoryToExcel = async (input: MedicineReportInput) => {
  const workbook = buildMedicineInventoryWorkbook(input);
  await downloadWorkbook(workbook, getFileName(input.target));
};
