import ExcelJS from "exceljs";
import type { DoctorChamberVisitRecord } from "../types";

const MIME_TYPE =
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

const money = (value: number): string =>
  `BDT ${value.toLocaleString("en-BD", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

export async function exportDoctorChamberToExcel(
  visits: DoctorChamberVisitRecord[],
  period: string,
  generatedBy: string,
) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = generatedBy;
  workbook.title = "Dr Sufia Khatun Chamber Report";
  workbook.subject = "Dr Sufia Khatun private chamber patient records";

  const worksheet = workbook.addWorksheet("Chamber Visits");
  worksheet.properties.defaultRowHeight = 20;
  worksheet.pageSetup = {
    orientation: "landscape",
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    paperSize: 9,
    margins: { left: 0.3, right: 0.3, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 },
  };
  worksheet.mergeCells("A1:J1");
  worksheet.getCell("A1").value = "Dr Sufia Khatun Private Chamber Report";
  worksheet.getCell("A1").font = { bold: true, size: 16, color: { argb: "FF0F172A" } };
  worksheet.getCell("A1").alignment = { horizontal: "center" };
  worksheet.mergeCells("A2:J2");
  worksheet.getCell("A2").value = `Period: ${period}`;
  worksheet.getCell("A2").alignment = { horizontal: "center" };
  worksheet.getCell("A2").font = { italic: true, color: { argb: "FF475569" } };
  worksheet.mergeCells("A3:J3");
  worksheet.getCell("A3").value = `Generated by: ${generatedBy}`;
  worksheet.getCell("A3").alignment = { horizontal: "center" };
  worksheet.getCell("A3").font = { italic: true, color: { argb: "FF475569" } };

  const header = worksheet.addRow([
    "#",
    "Visit No.",
    "Visit Date",
    "Patient",
    "Phone",
    "Consulting Doctor",
    "Ultra Sono",
    "Visiting Charge",
    "Other Charges",
    "Total",
  ]);
  header.height = 24;
  header.font = { bold: true, color: { argb: "FFFFFFFF" } };
  header.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF111827" } };
  header.alignment = { horizontal: "center", vertical: "middle", wrapText: true };

  visits.forEach((visit, index) => {
    const otherCharges = visit.fees.reduce((sum, fee) => sum + fee.amount, 0);
    worksheet.addRow([
      index + 1,
      visit.visitNumber,
      new Date(visit.visitDate),
      visit.patientFullName,
      visit.patientPhoneNumber || "N/A",
      visit.doctorName,
      visit.ultrasoundCharge,
      visit.visitingCharge,
      otherCharges,
      visit.totalAmount,
    ]);
  });

  worksheet.columns = [
    { width: 8 },
    { width: 18 },
    { width: 20 },
    { width: 28 },
    { width: 18 },
    { width: 28 },
    { width: 18 },
    { width: 20 },
    { width: 18 },
    { width: 18 },
  ];
  worksheet.views = [{ state: "frozen", ySplit: header.number }];
  worksheet.autoFilter = {
    from: { row: header.number, column: 1 },
    to: { row: header.number, column: 10 },
  };

  for (let rowNumber = header.number + 1; rowNumber <= worksheet.rowCount; rowNumber += 1) {
    const row = worksheet.getRow(rowNumber);
    row.eachCell((cell, columnNumber) => {
      cell.border = {
        top: { style: "thin", color: { argb: "FFD1D5DB" } },
        left: { style: "thin", color: { argb: "FFD1D5DB" } },
        bottom: { style: "thin", color: { argb: "FFD1D5DB" } },
        right: { style: "thin", color: { argb: "FFD1D5DB" } },
      };
      cell.alignment = { vertical: "middle", wrapText: true };
      if (columnNumber === 3) cell.numFmt = "dd mmm yyyy";
      if (columnNumber >= 7) cell.value = money(Number(cell.value));
    });
    if (rowNumber % 2 === 0) {
      row.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF8FAFC" } };
    }
  }

  if (visits.length === 0) {
    const emptyRow = worksheet.addRow(["No chamber visits found for this report."]);
    worksheet.mergeCells(`A${emptyRow.number}:J${emptyRow.number}`);
  }

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: MIME_TYPE });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `dr-sufia-khatun-chamber-${new Date().toISOString().slice(0, 10)}.xlsx`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
